# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxMemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxMemo
    pod 'RxSwift', '6.7.1'
    pod 'RxCocoa', '6.7.1'
    pod 'NSObject+Rx'
    pod 'Action'
    pod 'RxDataSources', '~> 5.0'
    pod "RxCoreData", "~> 1.0.0"

end
